// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Compat from "preact/compat";

var Ref = {};

var Children = {};

var Context = {};

var Fragment = {};

var StrictMode = {};

var Suspense = {};

function lazy_(load) {
  return Compat.lazy(async function () {
              return {
                      default: await load()
                    };
            });
}

var Uncurried = {};

var Elements = {};

export {
  Ref ,
  Children ,
  Context ,
  Fragment ,
  StrictMode ,
  Suspense ,
  lazy_ ,
  Uncurried ,
  Elements ,
}
/* preact/compat Not a pure module */
