// Generated by ReScript, PLEASE EDIT WITH CARE


var Root = {};

var Client = {
  Root: Root
};

var Ref = {};

var Props = {};

var Style;

export {
  Client ,
  Ref ,
  Props ,
  Style ,
}
/* No side effect */
