// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Preact from "preact";

function App(props) {
  var match = Preact.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return Preact.jsxs("div", {
              children: [
                Preact.jsx("h1", {
                      children: "What is this about?",
                      className: "text-3xl font-semibold"
                    }),
                Preact.jsx("p", {
                      children: "This is a simple template for a Vite project using ReScript & Tailwind CSS."
                    }),
                Preact.jsx("h2", {
                      children: "Fast Refresh Test",
                      className: "text-2xl font-semibold mt-5"
                    }),
                Preact.jsx("button", {
                      children: "count is " + match[0].toString(),
                      onClick: (function (param) {
                          setCount(function (count) {
                                return count + 1 | 0;
                              });
                        })
                    }),
                Preact.jsxs("p", {
                      children: [
                        "Edit ",
                        Preact.jsx("code", {
                              children: "src/App.res"
                            }),
                        " and save to test Fast Refresh."
                      ]
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* preact Not a pure module */
